name: Generate Hashes for release assets
on:
  release:
    types: [published]
jobs:
  hash:
    runs-on: ubuntu-latest
    steps:
      - uses: MCJack123/ghaction-generate-release-hashes@v3
        with:
          get-assets: true
          hash-type: sha256
          file-name: hashes-sha256.txt
      - uses: MCJack123/ghaction-generate-release-hashes@v3
        with:
          get-assets: true
          hash-type: sha512
          file-name: hashes-sha512.txt
      - uses: MCJack123/ghaction-generate-release-hashes@v3
        with:
          get-assets: true
          hash-type: md5
          file-name: hashes-md5.txt
      - uses: actions/upload-artifact@v2
        with:
          name: Asset Hashes
          path: hashes*.txt